runtime: python27
api_version: 1
service: default
threadsafe: true


libraries:
- name: ssl
  version: latest

handlers:
- url: /.*
  script: main.app

env_variables:
  # Replace with your Firebase project ID.
  FIREBASE_PROJECT_ID: 'vuejs-43051'
